export enum Cities {
  None = 0,
  Riyadh = 1,
  Jeddah = 2,
  Mecca = 3,
  Medina = 4,
  Dammam = 5,
  Khobar = 6,
  Taif = 7,
  Abha = 8,
  Buraidah = 9,
  KhamisMushait = 10,
  Najran = 11,
  Jubail = 12,
  Hail = 13,
  Jizan = 14,
  AlKhobar = 15,
  Yanbu = 16,
  Tabuk = 17,
  AlQassim = 18,
  AlMubarraz = 19,
  AlAhsa = 20,
  AlFaisaliyah = 21,
  Dhahran = 22,
  Kharj = 23,
  AlMadinaAlMunawwarah = 24,
  AlJouf = 25,
}
