export enum Permissions {
  CreateRole = 1,
  UpdateRole = 2,
  DeleteRole = 3,
  ViewRoles = 4,
  AssignUserToRole = 5,
  UnassignUserToRole = 6,
  CreateCompany = 50,
  UpdateCompany = 51,
  DeleteCompany = 52,
  ViewCompanies = 53,
  CreateFacility = 100,
  UpdateFacility = 101,
  DeleteFacility = 102,
  ViewFacilities = 103,
  CreateGuard = 150,
  UpdateGuard = 151,
  DeleteGuard = 152,
  ViewGuards = 153,
}
