export enum Permissions {
  CreateRole = 1,
  UpdateRole = 2,
  DeleteRole = 3,
  ViewRoles = 4,
  AssignUserToRole = 5,
  UnassignUserToRole = 6,
  ViewUsers = 7,
  // Company
  CreateCompany = 50,
  UpdateCompany = 51,
  DeleteCompany = 52,
  // Company Services
  CreateCompanyService = 54,
  UpdateCompanyService = 55,
  DeleteCompanyService = 56,
  ViewCompaniesService = 57,
  // Facility
  CreateFacility = 100,
  UpdateFacility = 101,
  DeleteFacility = 102,
  ViewFacilities = 103,
  // Guard
  CreateGuard = 150,
  UpdateGuard = 151,
  DeleteGuard = 152,
  ViewGuards = 153,
  // Ad
  CreateAd = 200,
  UpdateAd = 201,
  DeleteAd = 202,
  ViewAds = 203,
  // Ad Offer
  CreateAdOffer = 250,
  UpdateAdOffer = 251,
  HideAdOffer = 252,
  ShowAdOffer = 253,
  AcceptAdOffer = 254,
  RejectAdOffer = 255,
  CancelAdOffer = 256,
  ViewAdOffers = 257,
  // Contract
  CreateContract = 300,
  UpdateContract = 301,
  ViewContracts = 302,
  SignContract = 303,
  // Price Request Chat
  CreatePriceRequestChat = 350,
  CreatePriceOfferChat = 351,
  CreateAdOfferChat = 352,
  SendPriceOfferMessage = 354,
  SendAdOfferMessage = 355,
  ViewChatMessages = 356,
  // Price Request
  CreatePriceRequest = 400,
  UpdatePriceRequest = 401,
  RejectPriceRequest = 402,
  CancelPriceRequest = 403,
  ViewPriceRequests = 404,
  HidePriceRequest = 405,
  ShowPriceRequest = 406,
  // Price Offer
  CreatePriceOffer = 450,
  UpdatePriceOffer = 451,
  HidePriceOffer = 452,
  ShowPriceOffer = 453,
  AcceptPriceOffer = 454,
  RejectPriceOffer = 455,
  CancelPriceOffer = 456,
  ViewPriceOffers = 457,
  // Ticket
  CreateTicket = 500,
  CreateTicketMessage = 501,
  ViewSentTickets = 503,
  ViewTicketMessages = 504,
  CloseTicket = 505,
  // Custom Clause
  CreateCustomClause = 550,
  UpdateCustomClause = 551,
  DeleteCustomClause = 552,
  ViewCustomClauses = 553,
  // Security Certificate
  CreateSecurityCertificate = 650,
  UpdateSecurityCertificate = 651,
  DeleteSecurityCertificate = 652,
  ViewSecurityCertificate = 653,
  SendPriceRequestMessage = 3543,
}
