import { ErrorCodes } from "./error-codes";

export const errorCodeTranslator = {
    'ar': {
        [ErrorCodes.None]: '',
        [ErrorCodes.NotFound]: 'غير موجود',
        [ErrorCodes.Unauthorized]: 'غير مصرح',
        [ErrorCodes.Forbidden]: 'ممنوع',
        [ErrorCodes.Conflict]: 'تعارض',
        [ErrorCodes.Validation]: 'تحقق',
        [ErrorCodes.PhoneExists]: 'رقم الهاتف موجود',
        [ErrorCodes.EmailExists]: 'البريد الإلكتروني موجود',
        [ErrorCodes.UserNameExists]: 'اسم المستخدم موجود',
        [ErrorCodes.InvalidEmailOrPassword]: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
        [ErrorCodes.UnconfirmedEmail]: 'البريد الإلكتروني غير مؤكد',
        [ErrorCodes.UnregisteredEmail]: 'البريد الإلكتروني غير مسجل',
        [ErrorCodes.UserExists]: 'المستخدم موجود',
        [ErrorCodes.UserNotExists]: 'المستخدم غير موجود',
        [ErrorCodes.RoleExists]: 'الدور موجود',
        [ErrorCodes.RoleNotExists]: 'الدور غير موجود',
        [ErrorCodes.RemoveRoleFailed]: 'فشل إزالة الدور',
        [ErrorCodes.AssignUserRoleFailed]: 'فشل تعيين دور المستخدم',
        [ErrorCodes.UnassignUserRoleFailed]: 'فشل إلغاء تعيين دور المستخدم',
        [ErrorCodes.TicketExists]: 'التذكرة موجودة',
        [ErrorCodes.TicketNotExists]: 'التذكرة غير موجودة',
        [ErrorCodes.TicketClosed]: 'التذكرة مغلقة',
        [ErrorCodes.AdExists]: 'الإعلان موجود',
        [ErrorCodes.AdNotExists]: 'الإعلان غير موجود',
        [ErrorCodes.AdNotOpened]: 'الإعلان غير مفتوح',
        [ErrorCodes.AdOfferNotPending]: 'عرض الإعلان غير معلق',
        [ErrorCodes.PriceRequestExists]: 'طلب السعر موجود',
        [ErrorCodes.PriceRequestNotExists]: 'طلب السعر غير موجود',
        [ErrorCodes.PriceRequestNotPending]: 'طلب السعر غير معلق',
        [ErrorCodes.Unknown]: 'خطأ غير متوقع'
    },
    'en': {
        [ErrorCodes.None]: '',
        [ErrorCodes.NotFound]: 'Not Found',
        [ErrorCodes.Unauthorized]: 'Unauthorized',
        [ErrorCodes.Forbidden]: 'Forbidden',
        [ErrorCodes.Conflict]: 'Conflict',
        [ErrorCodes.Validation]: 'Validation',
        [ErrorCodes.PhoneExists]: 'Phone number exists',
        [ErrorCodes.EmailExists]: 'Email exists',
        [ErrorCodes.UserNameExists]: 'Username exists',
        [ErrorCodes.InvalidEmailOrPassword]: 'Invalid email or password',
        [ErrorCodes.UnconfirmedEmail]: 'Unconfirmed email',
        [ErrorCodes.UnregisteredEmail]: 'Unregistered email',
        [ErrorCodes.UserExists]: 'User exists',
        [ErrorCodes.UserNotExists]: 'User does not exist',
        [ErrorCodes.RoleExists]: 'Role exists',
        [ErrorCodes.RoleNotExists]: 'Role does not exist',
        [ErrorCodes.RemoveRoleFailed]: 'Failed to remove role',
        [ErrorCodes.AssignUserRoleFailed]: 'Failed to assign user role',
        [ErrorCodes.UnassignUserRoleFailed]: 'Failed to unassign user role',
        [ErrorCodes.TicketExists]: 'Ticket exists',
        [ErrorCodes.TicketNotExists]: 'Ticket does not exist',
        [ErrorCodes.TicketClosed]: 'Ticket closed',
        [ErrorCodes.AdExists]: 'Ad exists',
        [ErrorCodes.AdNotExists]: 'Ad does not exist',
        [ErrorCodes.AdNotOpened]: 'Ad not opened',
        [ErrorCodes.AdOfferNotPending]: 'Ad offer not pending',
        [ErrorCodes.PriceRequestExists]: 'Price request exists',
        [ErrorCodes.PriceRequestNotExists]: 'Price request does not exist',
        [ErrorCodes.PriceRequestNotPending]: 'Price request not pending',
        [ErrorCodes.Unknown]: 'Unknown error'
    }
};