import { ShiftType } from '../../shared/enums/shift-type';

export const openedOffers = [
  {
    id: 1,
    name: 'Al Nasr Insurance',
    imageUrl: 'photos/e1b70096-5bdd-44bd-ab98-2a536936e4b81.png',
    startDate: '2025-01-20',
    endDate: '2025-12-20',
    servicesNames: '7 rooms, 5 cars, 1 public organization',
    services: [
      {
        name: 'room',
        quantity: 7,
        shiftType: ShiftType.Morning,
        monthlyCost: 2500,
        dailyCost: 85,
      },
      {
        name: 'car',
        quantity: 5,
        shiftType: ShiftType.Night,
        monthlyCost: 3800,
        dailyCost: 125,
      },
      {
        name: 'organization',
        quantity: 1,
        shiftType: ShiftType.Night,
        monthlyCost: 5000,
        dailyCost: 170,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 2,
    name: 'Zad for Security',
    imageUrl: 'photos/zad-security.png',
    startDate: '2025-02-01',
    endDate: '2025-12-31',
    servicesNames: '5 rooms, 3 cars',
    services: [
      {
        name: 'room',
        quantity: 5,
        shiftType: ShiftType.Morning,
        monthlyCost: 2300,
        dailyCost: 75,
      },
      {
        name: 'car',
        quantity: 3,
        shiftType: ShiftType.Morning,
        monthlyCost: 3500,
        dailyCost: 110,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 3,
    name: 'SecurePlus Solutions',
    imageUrl: 'photos/secureplus-solutions.png',
    startDate: '2025-03-15',
    endDate: '2025-12-31',
    servicesNames: '10 rooms, 8 cars, 2 public organizations',
    services: [
      {
        name: 'room',
        quantity: 10,
        shiftType: ShiftType.Night,
        monthlyCost: 3000,
        dailyCost: 100,
      },
      {
        name: 'car',
        quantity: 8,
        shiftType: ShiftType.Morning,
        monthlyCost: 4500,
        dailyCost: 150,
      },
      {
        name: 'organization',
        quantity: 2,
        shiftType: ShiftType.Night,
        monthlyCost: 6000,
        dailyCost: 200,
      },
    ],
    status: 'pending',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 4,
    name: 'Elite Security',
    imageUrl: 'photos/elite-security.png',
    startDate: '2025-04-10',
    endDate: '2025-11-30',
    servicesNames: '12 rooms, 6 cars',
    services: [
      {
        name: 'room',
        quantity: 12,
        shiftType: ShiftType.Morning,
        monthlyCost: 2800,
        dailyCost: 95,
      },
      {
        name: 'car',
        quantity: 6,
        shiftType: ShiftType.Night,
        monthlyCost: 4000,
        dailyCost: 140,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 5,
    name: 'Guardians Corp',
    imageUrl: 'photos/guardians-corp.png',
    startDate: '2025-05-01',
    endDate: '2025-10-15',
    servicesNames: '8 rooms, 4 cars, 1 public organization',
    services: [
      {
        name: 'room',
        quantity: 8,
        shiftType: ShiftType.Night,
        monthlyCost: 2600,
        dailyCost: 90,
      },
      {
        name: 'car',
        quantity: 4,
        shiftType: ShiftType.Morning,
        monthlyCost: 3700,
        dailyCost: 120,
      },
      {
        name: 'organization',
        quantity: 1,
        shiftType: ShiftType.Morning,
        monthlyCost: 5200,
        dailyCost: 180,
      },
    ],
    status: 'pending',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 6,
    name: 'Defender Solutions',
    imageUrl: 'photos/defender-solutions.png',
    startDate: '2025-06-15',
    endDate: '2025-12-20',
    servicesNames: '15 rooms, 10 cars',
    services: [
      {
        name: 'room',
        quantity: 15,
        shiftType: ShiftType.Night,
        monthlyCost: 3200,
        dailyCost: 110,
      },
      {
        name: 'car',
        quantity: 10,
        shiftType: ShiftType.Night,
        monthlyCost: 5000,
        dailyCost: 170,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 7,
    name: 'Shield Protection',
    imageUrl: 'photos/shield-protection.png',
    startDate: '2025-07-01',
    endDate: '2025-11-30',
    servicesNames: '6 rooms, 3 cars',
    services: [
      {
        name: 'room',
        quantity: 6,
        shiftType: ShiftType.Morning,
        monthlyCost: 2400,
        dailyCost: 80,
      },
      {
        name: 'car',
        quantity: 3,
        shiftType: ShiftType.Morning,
        monthlyCost: 3600,
        dailyCost: 115,
      },
    ],
    status: 'inactive',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 8,
    name: 'Titan Security',
    imageUrl: 'photos/titan-security.png',
    startDate: '2025-08-01',
    endDate: '2025-12-31',
    servicesNames: '20 rooms, 15 cars, 3 public organizations',
    services: [
      {
        name: 'room',
        quantity: 20,
        shiftType: ShiftType.Night,
        monthlyCost: 3500,
        dailyCost: 130,
      },
      {
        name: 'car',
        quantity: 15,
        shiftType: ShiftType.Morning,
        monthlyCost: 5500,
        dailyCost: 190,
      },
      {
        name: 'organization',
        quantity: 3,
        shiftType: ShiftType.Night,
        monthlyCost: 6500,
        dailyCost: 220,
      },
    ],
    status: 'pending',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 9,
    name: 'Eagle Eye Protection',
    imageUrl: 'photos/eagle-eye.png',
    startDate: '2025-09-10',
    endDate: '2025-12-20',
    servicesNames: '10 rooms, 5 cars',
    services: [
      {
        name: 'room',
        quantity: 10,
        shiftType: ShiftType.Morning,
        monthlyCost: 2800,
        dailyCost: 100,
      },
      {
        name: 'car',
        quantity: 5,
        shiftType: ShiftType.Night,
        monthlyCost: 4200,
        dailyCost: 150,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 10,
    name: 'Guardian Angels Security',
    imageUrl: 'photos/guardian-angels.png',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    servicesNames: '5 rooms, 2 cars',
    services: [
      {
        name: 'room',
        quantity: 5,
        shiftType: ShiftType.Night,
        monthlyCost: 2200,
        dailyCost: 75,
      },
      {
        name: 'car',
        quantity: 2,
        shiftType: ShiftType.Morning,
        monthlyCost: 3300,
        dailyCost: 100,
      },
    ],
    status: 'inactive',
    expanded: false,
    isEditMode: false,
  },
];
export const securityOffers = [
  {
    id: 1,
    name: 'Al Nasr Insurance',
    imageUrl: 'photos/e1b70096-5bdd-44bd-ab98-2a536936e4b81.png',
    startDate: '2025-01-20',
    endDate: '2025-12-20',
    servicesNames: '7 rooms, 5 cars, 1 public organization',
    services: [
      {
        name: 'room',
        quantity: 7,
        shiftType: ShiftType.Morning,
        monthlyCost: 2500,
        dailyCost: 85,
      },
      {
        name: 'car',
        quantity: 5,
        shiftType: ShiftType.Night,
        monthlyCost: 3800,
        dailyCost: 125,
      },
      {
        name: 'organization',
        quantity: 1,
        shiftType: ShiftType.Night,
        monthlyCost: 5000,
        dailyCost: 170,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 2,
    name: 'Zad for Security',
    imageUrl: 'photos/e1b70096-5bdd-44bd-ab98-2a536936e4b81.png',
    startDate: '2025-01-20',
    endDate: '2025-12-20',
    servicesNames: '7 rooms, 5 cars, 1 public organization',
    services: [
      {
        name: 'room',
        quantity: 7,
        shiftType: ShiftType.Morning,
        monthlyCost: 2500,
        dailyCost: 85,
      },
      {
        name: 'car',
        quantity: 5,
        shiftType: ShiftType.Morning,
        monthlyCost: 3800,
        dailyCost: 125,
      },
      {
        name: 'organization',
        quantity: 1,
        shiftType: ShiftType.Morning,
        monthlyCost: 5000,
        dailyCost: 170,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 3,
    name: 'SecurePlus Solutions',
    imageUrl: 'photos/secureplus-solutions.png',
    startDate: '2025-03-15',
    endDate: '2025-12-31',
    servicesNames: '10 rooms, 8 cars, 2 public organizations',
    services: [
      {
        name: 'room',
        quantity: 10,
        shiftType: ShiftType.Night,
        monthlyCost: 3000,
        dailyCost: 100,
      },
      {
        name: 'car',
        quantity: 8,
        shiftType: ShiftType.Morning,
        monthlyCost: 4500,
        dailyCost: 150,
      },
      {
        name: 'organization',
        quantity: 2,
        shiftType: ShiftType.Night,
        monthlyCost: 6000,
        dailyCost: 200,
      },
    ],
    status: 'pending',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 4,
    name: 'Mohamed Nashaet',
    imageUrl: 'photos/e1b70096-5bdd-44bd-ab98-2a536936e4b81.png',
    startDate: '2025-01-20',
    endDate: '2025-12-20',
    servicesNames: '7 rooms, 5 cars, 1 public organization',
    services: [
      {
        name: 'room',
        quantity: 7,
        shiftType: ShiftType.Morning,
        monthlyCost: 2500,
        dailyCost: 85,
      },
      {
        name: 'car',
        quantity: 5,
        shiftType: ShiftType.Morning,
        monthlyCost: 3800,
        dailyCost: 125,
      },
      {
        name: 'organization',
        quantity: 1,
        shiftType: ShiftType.Morning,
        monthlyCost: 5000,
        dailyCost: 170,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 5,
    name: 'CityGuard Security',
    imageUrl: 'photos/cityguard-security.png',
    startDate: '2025-02-01',
    endDate: '2025-11-30',
    servicesNames: '12 rooms, 10 cars, 3 public organizations',
    services: [
      {
        name: 'room',
        quantity: 12,
        shiftType: ShiftType.Night,
        monthlyCost: 3300,
        dailyCost: 110,
      },
      {
        name: 'car',
        quantity: 10,
        shiftType: ShiftType.Morning,
        monthlyCost: 4500,
        dailyCost: 150,
      },
      {
        name: 'organization',
        quantity: 3,
        shiftType: ShiftType.Night,
        monthlyCost: 6000,
        dailyCost: 200,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 6,
    name: 'SmartClean Services',
    imageUrl: 'photos/smartclean-services.png',
    startDate: '2025-03-15',
    endDate: '2025-09-15',
    servicesNames: '8 rooms, 4 cars, 2 public organizations',
    services: [
      {
        name: 'room',
        quantity: 8,
        shiftType: ShiftType.Morning,
        monthlyCost: 2800,
        dailyCost: 95,
      },
      {
        name: 'car',
        quantity: 4,
        shiftType: ShiftType.Morning,
        monthlyCost: 3500,
        dailyCost: 120,
      },
      {
        name: 'organization',
        quantity: 2,
        shiftType: ShiftType.Night,
        monthlyCost: 5400,
        dailyCost: 180,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 7,
    name: 'EcoGuard Solutions',
    imageUrl: 'photos/ecoguard-solutions.png',
    startDate: '2025-05-10',
    endDate: '2025-12-31',
    servicesNames: '15 rooms, 8 cars, 4 public organizations',
    services: [
      {
        name: 'room',
        quantity: 15,
        shiftType: ShiftType.Morning,
        monthlyCost: 3300,
        dailyCost: 110,
      },
      {
        name: 'car',
        quantity: 8,
        shiftType: ShiftType.Night,
        monthlyCost: 4000,
        dailyCost: 140,
      },
      {
        name: 'organization',
        quantity: 4,
        shiftType: ShiftType.Morning,
        monthlyCost: 5500,
        dailyCost: 190,
      },
    ],
    status: 'active',
    expanded: false,
    isEditMode: false,
  },
  {
    id: 8,
    name: 'MaxPower Electricians',
    imageUrl: 'photos/maxpower-electricians.png',
    startDate: '2025-02-05',
    endDate: '2025-08-15',
    servicesNames: '10 rooms, 6 cars, 2 public organizations',
    services: [
      {
        name: 'room',
        quantity: 10,
        shiftType: ShiftType.Night,
        monthlyCost: 2700,
        dailyCost: 90,
      },
      {
        name: 'car',
        quantity: 6,
        shiftType: ShiftType.Morning,
        monthlyCost: 4200,
        dailyCost: 135,
      },
      {
        name: 'organization',
        quantity: 2,
        shiftType: ShiftType.Night,
        monthlyCost: 5000,
        dailyCost: 160,
      },
    ],
    status: 'inactive',
    expanded: false,
    isEditMode: false,
  },
];

interface Service {
  name: string;
  quantity: number;
  shiftType: ShiftType;
  monthlyCost: number;
  dailyCost: number;
}

export interface IOffer {
  id: number;
  name: string;
  imageUrl: string;
  startDate: string;
  endDate: string;
  servicesNames: string;
  services: Service[];
  status: 'active' | 'pending' | 'inactive';
  expanded: boolean;
  isEditMode: boolean;
}
